language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t harrydu/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true harrydu/react-test npm test

after_success:
  - docker build -t harrydu/multi-client ./client
  - docker build -t harrydu/multi-worker ./worker
  - docker build -t harrydu/multi-nginx ./nginx
  - docker build -t harrydu/multi-server ./server
  #login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push harrydu/multi-client
  - docker push harrydu/multi-worker
  - docker push harrydu/multi-nginx
  - docker push harrydu/multi-server

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-112346008503"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KET
